[{'name': 'data_science_project_logger', 'msg': 'Custom logger is working fine!', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 10, 'funcName': '<module>', 'created': 1758702956.65264, 'msecs': 652.0, 'relativeCreated': 0.0, 'thread': 22492, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 34544, 'message': 'Custom logger is working fine!'}sctime)s: INFO: main: Custom logger is working fine!]
[{'name': 'data_science_project_logger', 'msg': 'Custom logger is working fine!', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 10, 'funcName': '<module>', 'created': 1758787165.4461162, 'msecs': 446.0, 'relativeCreated': 7.834196090698242, 'thread': 35280, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 29564, 'message': 'Custom logger is working fine!'}sctime)s: INFO: main: Custom logger is working fine!]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787259.2313285, 'msecs': 231.0, 'relativeCreated': 5971.374273300171, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787259.2313285, 'msecs': 231.0, 'relativeCreated': 5971.374273300171, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787259.2467997, 'msecs': 246.0, 'relativeCreated': 5986.84549331665, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': BoxValueError('yaml file is empty'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'box.exceptions.BoxValueError'>, BoxValueError('yaml file is empty'), <traceback object at 0x000002A9AD744180>), 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1758787259.2467997, 'msecs': 246.0, 'relativeCreated': 5986.84549331665, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': 'yaml file is empty'}sctime)s: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "D:\Data Science\src\DataScienceProject\utils\common.py", line 18, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Data Science\main.py", line 16, in <module>
    obj.initiate_data_ingestion()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\src\DataScienceProject\config\configuration.py", line 10, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\src\DataScienceProject\utils\common.py", line 20, in read_yaml
    raise BoxValueError("yaml file is empty")
box.exceptions.BoxValueError: yaml file is empty
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787337.1517835, 'msecs': 151.0, 'relativeCreated': 257.4315071105957, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787337.1517835, 'msecs': 151.0, 'relativeCreated': 257.4315071105957, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': FileNotFoundError(2, 'No such file or directory'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x00000167AA1FA100>), 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1758787338.175241, 'msecs': 175.0, 'relativeCreated': 1280.8890342712402, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': "[Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'"}sctime)s: ERROR: main: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\Data Science\main.py", line 16, in <module>
    obj.initiate_data_ingestion()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
  File "D:\Data Science\src\DataScienceProject\components\data_ingestion.py", line 13, in download_file
    filename, headers= request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.11.12-windows-x86_64-none\Lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787532.280677, 'msecs': 280.0, 'relativeCreated': 320.7056522369385, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': FileNotFoundError(2, 'No such file or directory'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000016AE361DCC0>), 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1758787532.8843224, 'msecs': 884.0, 'relativeCreated': 924.3509769439697, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': "[Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'"}sctime)s: ERROR: main: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\Data Science\main.py", line 16, in <module>
    obj.initiate_data_ingestion()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
  File "D:\Data Science\src\DataScienceProject\components\data_ingestion.py", line 13, in download_file
    filename, headers= request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.11.12-windows-x86_64-none\Lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': 'file : artifacts/data_ingestion/data.zip downloaded successfully with following info: Connection: close\nContent-Length: 23329\nCache-Control: max-age=300\nContent-Security-Policy: default-src \'none\'; style-src \'unsafe-inline\'; sandbox\nContent-Type: application/zip\nETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"\nStrict-Transport-Security: max-age=31536000\nX-Content-Type-Options: nosniff\nX-Frame-Options: deny\nX-XSS-Protection: 1; mode=block\nX-GitHub-Request-Id: F166:246A48:32A99:619FF:68D4F709\nAccept-Ranges: bytes\nDate: Thu, 25 Sep 2025 08:12:41 GMT\nVia: 1.1 varnish\nX-Served-By: cache-maa10234-MAA\nX-Cache: HIT\nX-Cache-Hits: 0\nX-Timer: S1758787962.595613,VS0,VE310\nVary: Authorization,Accept-Encoding\nAccess-Control-Allow-Origin: *\nCross-Origin-Resource-Policy: cross-origin\nX-Fastly-Request-ID: ffdc48c36081ef07b20b420bfab4ea7e3a890dd2\nExpires: Thu, 25 Sep 2025 08:17:41 GMT\nSource-Age: 0\n\n', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 18, 'funcName': 'download_file', 'created': 1758787961.464723, 'msecs': 464.0, 'relativeCreated': 1190.958023071289, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'file : artifacts/data_ingestion/data.zip downloaded successfully with following info: Connection: close\nContent-Length: 23329\nCache-Control: max-age=300\nContent-Security-Policy: default-src \'none\'; style-src \'unsafe-inline\'; sandbox\nContent-Type: application/zip\nETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"\nStrict-Transport-Security: max-age=31536000\nX-Content-Type-Options: nosniff\nX-Frame-Options: deny\nX-XSS-Protection: 1; mode=block\nX-GitHub-Request-Id: F166:246A48:32A99:619FF:68D4F709\nAccept-Ranges: bytes\nDate: Thu, 25 Sep 2025 08:12:41 GMT\nVia: 1.1 varnish\nX-Served-By: cache-maa10234-MAA\nX-Cache: HIT\nX-Cache-Hits: 0\nX-Timer: S1758787962.595613,VS0,VE310\nVary: Authorization,Accept-Encoding\nAccess-Control-Allow-Origin: *\nCross-Origin-Resource-Policy: cross-origin\nX-Fastly-Request-ID: ffdc48c36081ef07b20b420bfab4ea7e3a890dd2\nExpires: Thu, 25 Sep 2025 08:17:41 GMT\nSource-Age: 0\n\n'}sctime)s: INFO: data_ingestion: file : artifacts/data_ingestion/data.zip downloaded successfully with following info: Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F166:246A48:32A99:619FF:68D4F709
Accept-Ranges: bytes
Date: Thu, 25 Sep 2025 08:12:41 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10234-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1758787962.595613,VS0,VE310
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ffdc48c36081ef07b20b420bfab4ea7e3a890dd2
Expires: Thu, 25 Sep 2025 08:17:41 GMT
Source-Age: 0

]
[{'name': 'data_science_project_logger', 'msg': 'extracted all the files to : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 27, 'funcName': 'extract_zip_file', 'created': 1758787961.4945073, 'msecs': 494.0, 'relativeCreated': 1220.7422256469727, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'extracted all the files to : artifacts/data_ingestion'}sctime)s: INFO: data_ingestion: extracted all the files to : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': '<module>', 'created': 1758787961.4948163, 'msecs': 494.0, 'relativeCreated': 1221.0512161254883, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x==========x]
