[{'name': 'data_science_project_logger', 'msg': 'Custom logger is working fine!', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 10, 'funcName': '<module>', 'created': 1758702956.65264, 'msecs': 652.0, 'relativeCreated': 0.0, 'thread': 22492, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 34544, 'message': 'Custom logger is working fine!'}sctime)s: INFO: main: Custom logger is working fine!]
[{'name': 'data_science_project_logger', 'msg': 'Custom logger is working fine!', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 10, 'funcName': '<module>', 'created': 1758787165.4461162, 'msecs': 446.0, 'relativeCreated': 7.834196090698242, 'thread': 35280, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 29564, 'message': 'Custom logger is working fine!'}sctime)s: INFO: main: Custom logger is working fine!]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787259.2313285, 'msecs': 231.0, 'relativeCreated': 5971.374273300171, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787259.2313285, 'msecs': 231.0, 'relativeCreated': 5971.374273300171, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787259.2467997, 'msecs': 246.0, 'relativeCreated': 5986.84549331665, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': BoxValueError('yaml file is empty'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'box.exceptions.BoxValueError'>, BoxValueError('yaml file is empty'), <traceback object at 0x000002A9AD744180>), 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1758787259.2467997, 'msecs': 246.0, 'relativeCreated': 5986.84549331665, 'thread': 13168, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 35588, 'message': 'yaml file is empty'}sctime)s: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "D:\Data Science\src\DataScienceProject\utils\common.py", line 18, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Data Science\main.py", line 16, in <module>
    obj.initiate_data_ingestion()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\src\DataScienceProject\config\configuration.py", line 10, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\src\DataScienceProject\utils\common.py", line 20, in read_yaml
    raise BoxValueError("yaml file is empty")
box.exceptions.BoxValueError: yaml file is empty
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787337.1517835, 'msecs': 151.0, 'relativeCreated': 257.4315071105957, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787337.1517835, 'msecs': 151.0, 'relativeCreated': 257.4315071105957, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787337.153795, 'msecs': 153.0, 'relativeCreated': 259.4430446624756, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': FileNotFoundError(2, 'No such file or directory'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x00000167AA1FA100>), 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1758787338.175241, 'msecs': 175.0, 'relativeCreated': 1280.8890342712402, 'thread': 30920, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24112, 'message': "[Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'"}sctime)s: ERROR: main: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\Data Science\main.py", line 16, in <module>
    obj.initiate_data_ingestion()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
  File "D:\Data Science\src\DataScienceProject\components\data_ingestion.py", line 13, in download_file
    filename, headers= request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.11.12-windows-x86_64-none\Lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787532.280677, 'msecs': 280.0, 'relativeCreated': 320.7056522369385, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787532.2882183, 'msecs': 288.0, 'relativeCreated': 328.2468318939209, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': FileNotFoundError(2, 'No such file or directory'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000016AE361DCC0>), 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1758787532.8843224, 'msecs': 884.0, 'relativeCreated': 924.3509769439697, 'thread': 37364, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 30088, 'message': "[Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'"}sctime)s: ERROR: main: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\Data Science\main.py", line 16, in <module>
    obj.initiate_data_ingestion()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
  File "D:\Data Science\src\DataScienceProject\components\data_ingestion.py", line 13, in download_file
    filename, headers= request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.11.12-windows-x86_64-none\Lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifcats/data_ingestion/data.zip'
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 14, 'funcName': '<module>', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758787960.5344815, 'msecs': 534.0, 'relativeCreated': 260.71643829345703, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': 'file : artifacts/data_ingestion/data.zip downloaded successfully with following info: Connection: close\nContent-Length: 23329\nCache-Control: max-age=300\nContent-Security-Policy: default-src \'none\'; style-src \'unsafe-inline\'; sandbox\nContent-Type: application/zip\nETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"\nStrict-Transport-Security: max-age=31536000\nX-Content-Type-Options: nosniff\nX-Frame-Options: deny\nX-XSS-Protection: 1; mode=block\nX-GitHub-Request-Id: F166:246A48:32A99:619FF:68D4F709\nAccept-Ranges: bytes\nDate: Thu, 25 Sep 2025 08:12:41 GMT\nVia: 1.1 varnish\nX-Served-By: cache-maa10234-MAA\nX-Cache: HIT\nX-Cache-Hits: 0\nX-Timer: S1758787962.595613,VS0,VE310\nVary: Authorization,Accept-Encoding\nAccess-Control-Allow-Origin: *\nCross-Origin-Resource-Policy: cross-origin\nX-Fastly-Request-ID: ffdc48c36081ef07b20b420bfab4ea7e3a890dd2\nExpires: Thu, 25 Sep 2025 08:17:41 GMT\nSource-Age: 0\n\n', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 18, 'funcName': 'download_file', 'created': 1758787961.464723, 'msecs': 464.0, 'relativeCreated': 1190.958023071289, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'file : artifacts/data_ingestion/data.zip downloaded successfully with following info: Connection: close\nContent-Length: 23329\nCache-Control: max-age=300\nContent-Security-Policy: default-src \'none\'; style-src \'unsafe-inline\'; sandbox\nContent-Type: application/zip\nETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"\nStrict-Transport-Security: max-age=31536000\nX-Content-Type-Options: nosniff\nX-Frame-Options: deny\nX-XSS-Protection: 1; mode=block\nX-GitHub-Request-Id: F166:246A48:32A99:619FF:68D4F709\nAccept-Ranges: bytes\nDate: Thu, 25 Sep 2025 08:12:41 GMT\nVia: 1.1 varnish\nX-Served-By: cache-maa10234-MAA\nX-Cache: HIT\nX-Cache-Hits: 0\nX-Timer: S1758787962.595613,VS0,VE310\nVary: Authorization,Accept-Encoding\nAccess-Control-Allow-Origin: *\nCross-Origin-Resource-Policy: cross-origin\nX-Fastly-Request-ID: ffdc48c36081ef07b20b420bfab4ea7e3a890dd2\nExpires: Thu, 25 Sep 2025 08:17:41 GMT\nSource-Age: 0\n\n'}sctime)s: INFO: data_ingestion: file : artifacts/data_ingestion/data.zip downloaded successfully with following info: Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F166:246A48:32A99:619FF:68D4F709
Accept-Ranges: bytes
Date: Thu, 25 Sep 2025 08:12:41 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10234-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1758787962.595613,VS0,VE310
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ffdc48c36081ef07b20b420bfab4ea7e3a890dd2
Expires: Thu, 25 Sep 2025 08:17:41 GMT
Source-Age: 0

]
[{'name': 'data_science_project_logger', 'msg': 'extracted all the files to : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 27, 'funcName': 'extract_zip_file', 'created': 1758787961.4945073, 'msecs': 494.0, 'relativeCreated': 1220.7422256469727, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': 'extracted all the files to : artifacts/data_ingestion'}sctime)s: INFO: data_ingestion: extracted all the files to : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': '<module>', 'created': 1758787961.4948163, 'msecs': 494.0, 'relativeCreated': 1221.0512161254883, 'thread': 26476, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 36780, 'message': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x==========x]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 15, 'funcName': '<module>', 'created': 1758792948.6925485, 'msecs': 692.0, 'relativeCreated': 10585.471153259277, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758792948.7242095, 'msecs': 724.0, 'relativeCreated': 10617.132186889648, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758792948.7262065, 'msecs': 726.0, 'relativeCreated': 10619.129180908203, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758792948.757661, 'msecs': 757.0, 'relativeCreated': 10650.583744049072, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758792948.7596586, 'msecs': 759.0, 'relativeCreated': 10652.581214904785, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758792948.7626576, 'msecs': 762.0, 'relativeCreated': 10655.580282211304, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': 'FIle already exists', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 20, 'funcName': 'download_file', 'created': 1758792948.763924, 'msecs': 763.0, 'relativeCreated': 10656.846523284912, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'FIle already exists'}sctime)s: INFO: data_ingestion: FIle already exists]
[{'name': 'data_science_project_logger', 'msg': 'extracted all the files to : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 27, 'funcName': 'extract_zip_file', 'created': 1758792948.7732127, 'msecs': 773.0, 'relativeCreated': 10666.135311126709, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'extracted all the files to : artifacts/data_ingestion'}sctime)s: INFO: data_ingestion: extracted all the files to : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 18, 'funcName': '<module>', 'created': 1758792948.7742088, 'msecs': 774.0, 'relativeCreated': 10667.131423950195, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x==========x]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Validation Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 25, 'funcName': '<module>', 'created': 1758792948.77521, 'msecs': 775.0, 'relativeCreated': 10668.132543563843, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': '>>>>> stage Data Validation Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758792948.7782109, 'msecs': 778.0, 'relativeCreated': 10671.133518218994, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758792948.780603, 'msecs': 780.0, 'relativeCreated': 10673.52557182312, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758792948.78389, 'msecs': 783.0, 'relativeCreated': 10676.812648773193, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758792948.78389, 'msecs': 783.0, 'relativeCreated': 10676.812648773193, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_validation', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758792948.7900114, 'msecs': 790.0, 'relativeCreated': 10682.934045791626, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': 'created directory at : artifacts/data_validation'}sctime)s: INFO: common: created directory at : artifacts/data_validation]
[{'name': 'data_science_project_logger', 'msg': PermissionError(13, 'Permission denied'), 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': (<class 'PermissionError'>, PermissionError(13, 'Permission denied'), <traceback object at 0x0000029BD4736700>), 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': '<module>', 'created': 1758792948.793003, 'msecs': 793.0, 'relativeCreated': 10685.925722122192, 'thread': 35292, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 24044, 'message': "[Errno 13] Permission denied: 'artifacts/data_ingestion'"}sctime)s: ERROR: main: [Errno 13] Permission denied: 'artifacts/data_ingestion']
Traceback (most recent call last):
  File "D:\Data Science\main.py", line 27, in <module>
    obj.initiate_data_validation()
  File "D:\Data Science\src\DataScienceProject\pipeline\data_validation_pipeline.py", line 18, in initiate_data_validation
    validation_status=data_validation.validate_data_columns()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\src\DataScienceProject\components\data_validation.py", line 29, in validate_data_columns
    raise e
  File "D:\Data Science\src\DataScienceProject\components\data_validation.py", line 13, in validate_data_columns
    data=pd.read_csv(self.config.unzip_data_dir)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "D:\Data Science\.venv\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'artifacts/data_ingestion'
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 15, 'funcName': '<module>', 'created': 1758793159.753109, 'msecs': 753.0, 'relativeCreated': 610.074520111084, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': '>>>>> stage Data Ingestion Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758793159.779722, 'msecs': 779.0, 'relativeCreated': 636.6875171661377, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758793159.779722, 'msecs': 779.0, 'relativeCreated': 636.6875171661377, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758793159.779722, 'msecs': 779.0, 'relativeCreated': 636.6875171661377, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758793159.779722, 'msecs': 779.0, 'relativeCreated': 636.6875171661377, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758793159.779722, 'msecs': 779.0, 'relativeCreated': 636.6875171661377, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'created directory at : artifacts/data_ingestion'}sctime)s: INFO: common: created directory at : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': 'FIle already exists', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 20, 'funcName': 'download_file', 'created': 1758793159.779722, 'msecs': 779.0, 'relativeCreated': 636.6875171661377, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'FIle already exists'}sctime)s: INFO: data_ingestion: FIle already exists]
[{'name': 'data_science_project_logger', 'msg': 'extracted all the files to : artifacts/data_ingestion', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\components\\data_ingestion.py', 'filename': 'data_ingestion.py', 'module': 'data_ingestion', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 27, 'funcName': 'extract_zip_file', 'created': 1758793159.7951267, 'msecs': 795.0, 'relativeCreated': 652.0922183990479, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'extracted all the files to : artifacts/data_ingestion'}sctime)s: INFO: data_ingestion: extracted all the files to : artifacts/data_ingestion]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 18, 'funcName': '<module>', 'created': 1758793159.7951267, 'msecs': 795.0, 'relativeCreated': 652.0922183990479, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': '>>>>> stage Data Ingestion Stage completed <<<<<\n\nx==========x'}sctime)s: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x==========x]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Validation Stage started <<<<<', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 25, 'funcName': '<module>', 'created': 1758793159.7961245, 'msecs': 796.0, 'relativeCreated': 653.0900001525879, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': '>>>>> stage Data Validation Stage started <<<<<'}sctime)s: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: config\\config.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758793159.7970605, 'msecs': 797.0, 'relativeCreated': 654.0260314941406, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'yaml file: config\\config.yaml loaded successfully'}sctime)s: INFO: common: yaml file: config\config.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: params.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758793159.8013253, 'msecs': 801.0, 'relativeCreated': 658.2908630371094, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'yaml file: params.yaml loaded successfully'}sctime)s: INFO: common: yaml file: params.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'yaml file: schema.yaml loaded successfully', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': 'read_yaml', 'created': 1758793159.8034089, 'msecs': 803.0, 'relativeCreated': 660.3744029998779, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'yaml file: schema.yaml loaded successfully'}sctime)s: INFO: common: yaml file: schema.yaml loaded successfully]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758793159.8034089, 'msecs': 803.0, 'relativeCreated': 660.3744029998779, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'created directory at : artifacts'}sctime)s: INFO: common: created directory at : artifacts]
[{'name': 'data_science_project_logger', 'msg': 'created directory at : artifacts/data_validation', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\utils\\common.py', 'filename': 'common.py', 'module': 'common', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 30, 'funcName': 'create_directories', 'created': 1758793159.804867, 'msecs': 804.0, 'relativeCreated': 661.8325710296631, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'created directory at : artifacts/data_validation'}sctime)s: INFO: common: created directory at : artifacts/data_validation]
[{'name': 'data_science_project_logger', 'msg': 'Data Validation is completed and all the columns are present in the data', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\src\\DataScienceProject\\pipeline\\data_validation_pipeline.py', 'filename': 'data_validation_pipeline.py', 'module': 'data_validation_pipeline', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 20, 'funcName': 'initiate_data_validation', 'created': 1758793159.8487465, 'msecs': 848.0, 'relativeCreated': 705.712080001831, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': 'Data Validation is completed and all the columns are present in the data'}sctime)s: INFO: data_validation_pipeline: Data Validation is completed and all the columns are present in the data]
[{'name': 'data_science_project_logger', 'msg': '>>>>> stage Data Validation Stage completed <<<<<\n\nx==========x', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'D:\\Data Science\\main.py', 'filename': 'main.py', 'module': 'main', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 28, 'funcName': '<module>', 'created': 1758793159.8487465, 'msecs': 848.0, 'relativeCreated': 705.712080001831, 'thread': 35196, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 33888, 'message': '>>>>> stage Data Validation Stage completed <<<<<\n\nx==========x'}sctime)s: INFO: main: >>>>> stage Data Validation Stage completed <<<<<

x==========x]
